In [1]:
from aoc import read_file

In [142]:
lines = read_file('20221208_test.txt').split('\n')

# Part 1

In [143]:
import numpy as np

In [144]:
a = np.array([
    [int(c) for c in line]
    for line in lines
])

In [145]:
a

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [158]:
# From top 'cumulative max'
np.maximum.accumulate(a)

array([[3, 0, 3, 7, 3],
       [3, 5, 5, 7, 3],
       [6, 5, 5, 7, 3],
       [6, 5, 5, 7, 9],
       [6, 5, 5, 9, 9]])

In [160]:
# To compare columnwise, create a shifted copy:
def shift_down(a):
    top = np.ones((1, a.shape[1]), dtype=int) * -1
    
    return np.concatenate([top, a[:-1,:]])

shift_down(np.maximum.accumulate(a))

array([[-1, -1, -1, -1, -1],
       [ 3,  0,  3,  7,  3],
       [ 3,  5,  5,  7,  3],
       [ 6,  5,  5,  7,  3],
       [ 6,  5,  5,  7,  9]])

In [161]:
def compare_top(a):
    shifted_a = shift_down(a)
    # return np.minimum.accumulate(shifted_a < a)
    return shifted_a < a

# This gets us the trees that are visible from the top
compare_top(np.maximum.accumulate(a))

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False,  True, False]])

In [162]:
compare_top(np.maximum.accumulate(a.T)).T

array([[ True, False, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [148]:
# Do this from each side

top = compare_top(np.maximum.accumulate(a))

left = compare_top(np.maximum.accumulate(a.T)).T

bottom = np.flip(compare_top(np.maximum.accumulate(np.flip(a, axis=0))), axis=0)

right = np.flip(compare_top(np.maximum.accumulate(np.flip(a.T, axis=0))), axis=0).T

In [164]:
((top + left + bottom + right) > 0)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [165]:
((top + left + bottom + right) > 0).sum().sum()

21

# Part 2

In [150]:
a

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [154]:
def look_down(a):
    """Calculates how many trees can be seen from each position by looking down"""
    result = np.zeros(a.shape, int)

    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            v = a[i, j]
            count = 0
            for k in range(i+1, a.shape[0]):
                count += 1
                if a[k, j] >= a[i, j]:
                    break
            result[i, j] = count
    
    return result

In [155]:
look_down(a)

array([[2, 1, 1, 4, 3],
       [1, 1, 2, 1, 1],
       [2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0]])

In [156]:
top2 = look_down(a)

left2 = look_down(a.T).T

bottom2 = np.flip(look_down(np.flip(a, axis=0)), axis=0)

right2 = np.flip(look_down(np.flip(a.T, axis=0)), axis=0).T

In [157]:
np.max((top2 * left2 * bottom2 * right2))

8