In [1]:
from aoc import read_file

In [130]:
lines = read_file('20221208.txt').split('\n')

# Part 1

In [131]:
import numpy as np

In [132]:
a = np.array([
    [int(c) for c in line]
    for line in lines
])

In [133]:
a

array([[4, 2, 2, ..., 1, 2, 1],
       [3, 0, 1, ..., 1, 3, 4],
       [4, 1, 0, ..., 3, 4, 3],
       ...,
       [3, 3, 2, ..., 2, 3, 1],
       [1, 1, 0, ..., 1, 3, 1],
       [2, 3, 1, ..., 1, 1, 4]])

In [134]:
# From top 'cumulative max'
np.maximum.accumulate(a)

array([[4, 2, 2, ..., 1, 2, 1],
       [4, 2, 2, ..., 1, 3, 4],
       [4, 2, 2, ..., 3, 4, 4],
       ...,
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7],
       [7, 7, 7, ..., 7, 7, 7]])

In [135]:
# To compare columnwise, create a shifted copy:
def shift_down(a):
    top = np.ones((1, a.shape[1]), dtype=int) * -1
    
    return np.concatenate([top, a[:-1,:]])

def compare_top(a):
    shifted_a = shift_down(a)
    # return np.minimum.accumulate(shifted_a < a)
    return shifted_a < a

# This gets us the trees that are visible from the top
compare_top(np.maximum.accumulate(a))

array([[ True,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False,  True,  True],
       [False, False, False, ...,  True,  True, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [136]:
# Do this from each side

top = compare_top(np.maximum.accumulate(a))

left = compare_top(np.maximum.accumulate(a.T)).T

bottom = np.flip(compare_top(np.maximum.accumulate(np.flip(a, axis=0))), axis=0)

right = np.flip(compare_top(np.maximum.accumulate(np.flip(a.T, axis=0))), axis=0).T

In [137]:
((top + left + bottom + right) > 0).sum().sum()

1543

# Part 2

In [138]:
a

array([[4, 2, 2, ..., 1, 2, 1],
       [3, 0, 1, ..., 1, 3, 4],
       [4, 1, 0, ..., 3, 4, 3],
       ...,
       [3, 3, 2, ..., 2, 3, 1],
       [1, 1, 0, ..., 1, 3, 1],
       [2, 3, 1, ..., 1, 1, 4]])

In [139]:
def look_down(a):
    """Calculates how many trees can be seen from each position by looking down"""
    result = np.zeros(a.shape, int)

    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            v = a[i, j]
            count = 0
            for k in range(i+1, a.shape[0]):
                count += 1
                if a[k, j] >= a[i, j]:
                    break
            result[i, j] = count
    
    return result

In [140]:
top2 = look_down(a)

left2 = look_down(a.T).T

bottom2 = np.flip(look_down(np.flip(a, axis=0)), axis=0)

right2 = np.flip(look_down(np.flip(a.T, axis=0)), axis=0).T

In [141]:
np.max((top2 * left2 * bottom2 * right2))

595080